<?php

return [
    'sheet_name' => 'Estructura DI',
    'header_row' => 3,
    'data_start_row' => 4,
    'columns' => 35,

    'fields' => [
        1  => ['name' => 'Tipo de documento', 'type' => 'A', 'min' => 2, 'max' => 2, 'required' => true,
            'allowed' => ['CC','TI','CE','PA','RC','PE','MS','AS','CD','NV','PT','SC','CN','DE']],
        2  => ['name' => 'Número de identificación', 'type' => 'A', 'min' => 1, 'max' => 20, 'required' => true],
        3  => ['name' => 'Fecha de actividad demanda inducida', 'type' => 'F', 'min' => 10, 'max' => 10, 'required' => true],
        4  => ['name' => 'Elemento demanda inducida', 'type' => 'A', 'min' => 1, 'max' => 30, 'required' => true,
            'allowed' => ['SMS','Llamada telefónica','Material Educativo','Visita preventiva de salud','Jornada de salud','Campaña','Búsqueda Activa','Sala Espera']],
        5  => ['name' => 'Tipo de elemento demanda inducida', 'type' => 'A', 'min' => 1, 'max' => 50, 'required' => true,
            'allowed' => ['Mensaje','Comunicación telefónica','Comunicación IVR','Volante','Afiche']],
        6  => ['name' => 'Objetivo', 'type' => 'A', 'min' => 1, 'max' => 30, 'required' => true,
            'allowed' => ['Inducción al programa','Conocimiento estado salud','Autocuidado','Seguimiento','Educación']],
        7  => ['name' => 'Número de telefono con el que se establece el contacto', 'type' => 'A', 'min' => 1, 'max' => 30],
        8  => ['name' => 'Clasificación del seguimiento', 'type' => 'A', 'min' => 1, 'max' => 11,
            'allowed' => ['Efectivo','No efectivo']],
        9  => ['name' => 'Persona que recibe la llamada', 'type' => 'A', 'min' => 1, 'max' => 120],
        10 => ['name' => 'Relación con el usuario', 'type' => 'A', 'min' => 0, 'max' => 20,
            'allowed' => ['Usuario','Hijo(a)','Padre','Madre','Hermano','Tío','Amigo','Otro. Cual']],
        11 => ['name' => 'Fecha de llamada', 'type' => 'F', 'min' => 10, 'max' => 10],
        12 => ['name' => 'hora de llamada', 'type' => 'H', 'min' => 5, 'max' => 5],
        13 => ['name' => 'Texto de la llamada', 'type' => 'A', 'min' => 1, 'max' => 7000],
        14 => ['name' => 'Presenta barreras o dificultades para el acceso al tratamiento?', 'type' => 'A', 'min' => 2, 'max' => 2,
            'allowed' => ['SI','NO']],
        15 => ['name' => 'Area con la que presenta la dificultad?', 'type' => 'A', 'min' => 1, 'max' => 3,
            'allowed' => ['IPS','EPS']],
        16 => ['name' => 'Area de la EPS', 'type' => 'A', 'min' => 1, 'max' => 50,
            'allowed' => ['Afiliaciones','Autorizaciones','Otra','Dificultades para la cita','Inoportunidad de la atención','Atención en la IPS con personal o profesional de salud','Entrega de medicamentos','Realización de procedimientos']],
        17 => ['name' => 'Resumen de las actividades realizadas durante el seguimiento', 'type' => 'A', 'min' => 1, 'max' => 50,
            'allowed' => ['Gestión de citas exámenes o autorizaciones','Canalización a programas','Educación en salud','Acompañamiento','Ninguna']],
        18 => ['name' => 'Condición final usuario', 'type' => 'A', 'min' => 1, 'max' => 10,
            'allowed' => ['VIVO','MUERTO']],
        19 => ['name' => 'Soportes recuperados', 'type' => 'A', 'min' => 1, 'max' => 200],
        20 => ['name' => 'Departamento', 'type' => 'A', 'min' => 1, 'max' => 50],
        21 => ['name' => 'Municipio', 'type' => 'A', 'min' => 1, 'max' => 50],
        22 => ['name' => 'Barrio o vereda', 'type' => 'A', 'min' => 1, 'max' => 50],
        23 => ['name' => 'Número telefono', 'type' => 'N', 'min' => 1, 'max' => 30],
        24 => ['name' => 'Correo electronico', 'type' => 'A', 'min' => 1, 'max' => 120],
        25 => ['name' => 'Resultado de llamada', 'type' => 'A', 'min' => 1, 'max' => 40,
            'allowed' => ['Número equivocado','Número no existe','Sistema correo de voz','Otro']],
        26 => ['name' => 'Fecha de envío', 'type' => 'F', 'min' => 10, 'max' => 10],
        27 => ['name' => 'Hora de envío', 'type' => 'H', 'min' => 5, 'max' => 5],
        28 => ['name' => 'Texto del mensaje', 'type' => 'A', 'min' => 1, 'max' => 500],
        29 => ['name' => 'Fecha de visita', 'type' => 'F', 'min' => 10, 'max' => 10],
        30 => ['name' => 'Resumen de visita', 'type' => 'A', 'min' => 1, 'max' => 4000],
        31 => ['name' => 'Motivo de visita no efectiva', 'type' => 'A', 'min' => 1, 'max' => 30,
            'allowed' => ['Dirección errónea','Dirección no encontrada','No vive allí','Nadie atiende la visita','No está interesada','Otro','Olvidó la cita']],
        32 => ['name' => 'Persona que realiza el seguimiento', 'type' => 'A', 'min' => 1, 'max' => 120, 'required' => true],
        33 => ['name' => 'Área', 'type' => 'A', 'min' => 1, 'max' => 30, 'required' => true,
            'allowed' => ['HECSAP','PYMS','Rutas Riesgo','Salud comunitaria','Salud Pública']],
        34 => ['name' => 'Programa', 'type' => 'A', 'min' => 1, 'max' => 50, 'required' => true],
        35 => ['name' => 'Fecha de asignacion de cita', 'type' => 'F', 'min' => 10, 'max' => 10, 'required' => true],
    ],

    'programs' => [
        'HECSAP' => [
            'Alteraciones nutricionales','Anemia','Asma','Cardio-Cerebro-Vascular-Metabólico',
            'Condición materno - perinatal','Defectos congénitos','Desnutrición en menores de 5 años o DNT',
            'Diabetes','Difteria','Discapacidad','DNT','Encefalitis Equina','Enfermedad Diarreica Aguda',
            'Enfermedad Renal Crónica','Enfermedades Infecciosas','Enfermedades respiratorias crónicas',
            'Enfermedades Zoonóticas','Epilepsia','EPOC','Falla cardiaca','Fiebre amarilla','Hepatitis B y C',
            'Hipertensión Arterial','Infección Respiratoria Aguda','Meningitis','Morbilidad Materna Extrema',
            'Mortalidad en menores de 5 años','Mortalidad materna','Mortalidad perinatal y neonatal',
            'Parotiditis','Rubeola','Ruta Materno perinatal','Sarampión','Sarampión y Rubeola','Sífilis',
            'Sífilis congénita','Sífilis gestacional','Síndrome de Rubeola Congénita','Tétanos accidental',
            'Tétanos neonatal','Tosferina','Tuberculosis','Ulcera Gastrointestinal',
        ],
        'PYMS' => [
            'Adolescencia','Adultez','DT cáncer colorectal','DT cáncer cuello uterino','DT Cáncer infantil',
            'DT cáncer mama','DT cáncer próstata','Estrategia 4X4','Habitos de vida saludable','Infancia',
            'Juventud','Lactancia materna','Planificación familiar','Primera Infancia','Salud ambiental',
            'Salud Mental','Salud Oral','Salud sexual y reproductiva','Salud visual','Salud auditiva',
            'Tamizaje de RCV','Vacunación','Vejez',
        ],
        'Rutas Riesgo' => [
            'Accidentes y Enfermedad laborales','Agresiones, accidentes y traumas','Alteraciones nutricionales',
            'Alteraciones y trastornos de la audición y comunicación','Alteraciones y trastornos de la salud bucal',
            'Alteraciones y trastornos visuales','Anticoagulados','Asma','Bajo peso al nacer','Cáncer',
            'Cáncer de mama y cuello uterino','Cáncer en menores de 18 años','Cardio-Cerebro-Vascular-Metabólico',
            'Cesación de tabaco','Condición materno - perinatal','Consumo sustancias psicoactivas','Crónico complejo',
            'Defectos congénitos','Desnutrición en menores de 5 años o DNT','Diabetes','Discapacidad','DNT',
            'Enfermedad Diarreica Aguda','Enfermedad Renal Crónica','Enfermedades Huérfanas o raras',
            'Enfermedades Infecciosas','Enfermedades respiratorias crónicas',
            'Enfermedades y accidentes relacionados con el medio ambiente','Enfermedades Zoonóticas',
            'Epilepsia','EPOC','Exposición a flúor','Falla cardiaca','Hipertensión Arterial',
            'Infección Respiratoria Aguda','Intento de suicidio','Interrupción Voluntaria del Embarazo',
            'Morbilidad Materna Extrema','Mortalidad en menores de 5 años','Mortalidad materna',
            'Mortalidad perinatal y neonatal','Preconcepcional','Prematurez','Riesgo de desnutrición',
            'Ruta Materno perinatal','Sífilis congénita','Sífilis gestacional','Tamizaje neonatal',
            'Trastornos asociados al uso de SPA','Trastornos degenerativos, neuropatías y autoinmunes',
            'Trastornos mentales y del comportamiento','Victimas de agente químico','Vigilancia violencias',
            'VIH','Violencia de genero','Violencia intrafamiliar','Violencia relacionada con el conflicto armado',
            'Violencia sexual','Violencias',
        ],
        'Salud comunitaria' => ['Modelo de gestión extramural'],
        'Salud Pública' => [
            'Accidente ofídico','Agresiones por Animales Potencialmente Transmisores de Rabia','Chagas',
            'Chikunguña','Cólera','COVID-19','Dengue','Dengue Grave','Difteria','Ebola','Encefalitis Equina',
            'Enfermedad de Creutzfeldt Jakob','Enfermedad transmitida por alimentos',
            'Enfermedades Transmitida por Vectores','Evento supuestamente atribuido a la vacunación',
            'Fiebre amarilla','Fiebre tifoidea y paratifoidea','Hepatitis A','Hepatitis B y C',
            'Hipotiroidismo Congénito','Intoxicaciones','Leishmaniasis','Lepra','Leptospirosis',
            'Lesiones por artefactos explosivos','Malaria','Meningitis','Oncocercosis','Parálisis flácida Aguda',
            'Parotiditis','Rabia humana','Rubeola','Sarampión','Sarampión y Rubeola','Sífilis',
            'Síndrome de Rubeola Congénita','Tétanos accidental','Tétanos neonatal','Tosferina','Tracoma',
            'Tuberculosis','Varicela','Viruela símica','Zika',
        ],
    ],
];
