<?php

return [
    'sheets' => [
        'control' => [
            'name' => '1 - Control',
            'record_type' => 1,
            'columns' => [
                ['name' => 'Tipo de registro', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1']],
                ['name' => 'Tipo de identificación de la entidad reportadora', 'type' => 'A', 'required' => true, 'max' => 2, 'allowed' => ['NI']],
                ['name' => 'Número de identificación de la entidad reportadora', 'type' => 'N', 'required' => true, 'max' => 12],
                ['name' => 'Código de la entidad reportadora', 'type' => 'A', 'required' => true, 'max' => 6],
                ['name' => 'Fecha inicial del periodo de información reportada', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Fecha final del periodo de información reportada', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Total de registros de detalle', 'type' => 'N', 'required' => true, 'max' => 10],
            ],
        ],

        'identificaciones' => [
            'name' => '2 - ID gestantes',
            'record_type' => 2,
            'columns' => [
                ['name' => 'Tipo de registro', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['2']],
                ['name' => 'Consecutivo de registro', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'País de nacionalidad', 'type' => 'N', 'required' => true, 'max' => 3],
                ['name' => 'Código DANE Municipio de residencia', 'type' => 'N', 'required' => true, 'max' => 5],
                ['name' => 'Zona territorial de residencia', 'type' => 'A', 'required' => true, 'max' => 1, 'allowed' => ['U', 'R']],
                ['name' => 'Código de habilitación IPS primaria', 'type' => 'N', 'required' => true, 'max' => 12],
                ['name' => 'Tipo de documento de la usuaria', 'type' => 'A', 'required' => true, 'max' => 2],
                ['name' => 'Número de identificación de la usuaria', 'type' => 'A', 'required' => true, 'max' => 17],
                ['name' => 'Primer apellido de la usuaria', 'type' => 'A', 'required' => true, 'max' => 60],
                ['name' => 'Segundo apellido de la usuaria', 'type' => 'A', 'required' => false, 'max' => 60],
                ['name' => 'Primer nombre de la usuaria', 'type' => 'A', 'required' => true, 'max' => 60],
                ['name' => 'Segundo nombre de la usuaria', 'type' => 'A', 'required' => false, 'max' => 60],
                ['name' => 'Fecha de nacimiento', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Código de pertenencia étnica', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2','3','4','5','6','7']],
                ['name' => 'Código de ocupación', 'type' => 'N', 'required' => true, 'max' => 4],
                ['name' => 'Código de nivel educativo', 'type' => 'N', 'required' => true, 'max' => 2],
                ['name' => 'Fecha probable de parto', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Dirección de la residencia de la usuaria', 'type' => 'T', 'required' => true, 'max' => 200],
                ['name' => 'Antecedente de hipertensión crónica', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Antecedente de preeclampsia', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Antecedente de diabetes', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Antecedente de LES o enfermedad autoinmune', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Antecedente de síndrome metabólico', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Antecedente de ERC', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Antecedente de trombofilia o trombosis venosa profunda', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Antecedente de anemia de células falciformes', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Antecedente de sepsis durante gestaciones previas', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Consumo de tabaco durante la gestación actual', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Periodo intergenésico', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['0','1','2','3']],
                ['name' => 'Embarazo múltiple', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Método de concepción', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2','3']],
            ],
        ],

        'atenciones' => [
            'name' => '3 - Atenciones',
            'record_type' => 3,
            'columns' => [
                ['name' => 'Tipo de registro', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['3']],
                ['name' => 'Consecutivo de registro', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Tipo de documento de la usuaria', 'type' => 'A', 'required' => true, 'max' => 2],
                ['name' => 'Número de identificación de la usuaria', 'type' => 'A', 'required' => true, 'max' => 17],
                ['name' => 'Fecha de la tecnología en salud', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Código CUPS de la tecnología en salud', 'type' => 'N', 'required' => true, 'max' => 6],
                ['name' => 'Finalidad de la tecnología en salud', 'type' => 'N', 'required' => true, 'max' => 2],
                ['name' => 'Clasificación del riesgo gestacional', 'type' => 'N', 'required' => true, 'max' => 2, 'allowed' => ['4','5','21']],
                ['name' => 'Clasificación del riesgo de preeclampsia', 'type' => 'N', 'required' => true, 'max' => 2, 'allowed' => ['4','5','21']],
                ['name' => 'Suministro de ácido acetilsalicílico - ASA', 'type' => 'N', 'required' => true, 'max' => 2, 'allowed' => ['0','1','21']],
                ['name' => 'Suministro de ácido fólico', 'type' => 'N', 'required' => true, 'max' => 2, 'allowed' => ['0','1','21']],
                ['name' => 'Suministro de sulfato ferroso', 'type' => 'N', 'required' => true, 'max' => 2, 'allowed' => ['0','1','21']],
                ['name' => 'Suministro de calcio', 'type' => 'N', 'required' => true, 'max' => 2, 'allowed' => ['0','1','21']],
                ['name' => 'Fecha de suministro de anticonceptivo post evento obstétrico', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Suministro de anticonceptivo post evento obstétrico', 'type' => 'N', 'required' => true, 'max' => 2, 'allowed' => ['0','1','2','3','4','5','6','7','8','9','10','13','14','15']],
                ['name' => 'Fecha de salida de aborto, parto o cesárea', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Fecha de terminación de la gestación', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Tipo de terminación de la gestación', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['0','1','2','3','4']],
                ['name' => 'Tensión arterial sistólica', 'type' => 'N', 'required' => false, 'max' => 3],
                ['name' => 'Tensión arterial diastólica', 'type' => 'N', 'required' => false, 'max' => 3],
                ['name' => 'Índice de masa corporal', 'type' => 'D', 'required' => false, 'max' => 4],
                ['name' => 'Resultado de la hemoglobina', 'type' => 'D', 'required' => false, 'max' => 4],
                ['name' => 'Índice de pulsatilidad de arterias uterinas', 'type' => 'D', 'required' => false, 'max' => 4],
            ],
        ],

        'seguimientos' => [
            'name' => '4 - Seguimientos',
            'record_type' => 4,
            'columns' => [
                ['name' => 'Tipo de registro', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['4']],
                ['name' => 'Consecutivo de registro', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Tipo de documento de la usuaria', 'type' => 'A', 'required' => true, 'max' => 2],
                ['name' => 'Número de identificación de la usuaria', 'type' => 'A', 'required' => true, 'max' => 17],
                ['name' => 'Tipo de caso', 'type' => 'T', 'required' => true, 'max' => 30],
                ['name' => 'Fecha de seguimiento', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Tipo de seguimiento', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2','3','4']],
                ['name' => 'Asignación de cita por profesional de medicina', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Asignación de cita por medicina especializada', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Referencia a institución de mayor complejidad', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Asignación de cita para procedimientos', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Canalización a entrega de resultados de laboratorio', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Entrega de medicamentos', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Información para el cuidado de la salud', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
            ],
        ],

        'urgencias' => [
            'name' => '5 - Urgencias',
            'record_type' => 5,
            'columns' => [
                ['name' => 'Tipo de registro', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['5']],
                ['name' => 'Consecutivo de registro', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Tipo de documento de la usuaria', 'type' => 'A', 'required' => true, 'max' => 2],
                ['name' => 'Número de identificación de la usuaria', 'type' => 'A', 'required' => true, 'max' => 17],
                ['name' => 'Fecha de ingreso', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Código de habilitación IPS de internación', 'type' => 'N', 'required' => true, 'max' => 12],
                ['name' => 'Servicio del grupo de internación', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2','3','4']],
                ['name' => 'Tensión arterial sistólica', 'type' => 'N', 'required' => true, 'max' => 3],
                ['name' => 'Tensión arterial diastólica', 'type' => 'N', 'required' => true, 'max' => 3],
                ['name' => 'Frecuencia respiratoria', 'type' => 'N', 'required' => true, 'max' => 2],
                ['name' => 'Frecuencia cardiaca', 'type' => 'N', 'required' => true, 'max' => 3],
                ['name' => '% O2 requerido', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2','3']],
                ['name' => 'Temperatura', 'type' => 'D', 'required' => true, 'max' => 4],
                ['name' => 'Estado de conciencia', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Interconsulta por Telexperticia', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Interconsulta por teleapoyo', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Código habilitación IPS que realiza interconsulta', 'type' => 'N', 'required' => true, 'max' => 12],
                ['name' => 'Fecha de salida de la internación', 'type' => 'F', 'required' => true, 'max' => 10],
            ],
        ],
    ],
];