<?php

$personFields = [
    ['name' => 'Tipo de identificación del usuario', 'type' => 'A', 'required' => true, 'max' => 2, 'allowed' => ['RC','TI','CC','CE','PA','CD','PT','SC','PE','AS','MS','CN','NV']],
    ['name' => 'Número de identificación del usuario', 'type' => 'A', 'required' => true, 'max' => 16],
    ['name' => 'Fecha de nacimiento del usuario', 'type' => 'F', 'required' => true, 'max' => 10],
    ['name' => 'Sexo del usuario', 'type' => 'A', 'required' => true, 'max' => 1, 'allowed' => ['H','M','I']],
    ['name' => 'Primer apellido del usuario', 'type' => 'A', 'required' => true, 'max' => 60, 'uppercase' => true],
    ['name' => 'Segundo apellido del usuario', 'type' => 'A', 'required' => false, 'max' => 60, 'uppercase' => true],
    ['name' => 'Primer nombre del usuario', 'type' => 'A', 'required' => true, 'max' => 60, 'uppercase' => true],
    ['name' => 'Segundo nombre del usuario', 'type' => 'A', 'required' => false, 'max' => 60, 'uppercase' => true],
    ['name' => 'Código de la EAPB del usuario', 'type' => 'A', 'required' => true, 'max' => 6],
];

return [
    'control_sheet' => 'tipo1',
    'control_total_index' => 6,

    'sheet_order' => [
        'tipo1',
        'tipo2',
        'tipo3',
        'tipo4',
        'tipo5',
        'tipo6',
    ],

    'validation' => [
        // En este formato, cada tipo de detalle inicia su propio consecutivo en 1.
        'continuous_consecutives' => true,
        'validate_control_total' => true,
    ],

    'sheets' => [
        'tipo1' => [
            'name' => 'Tipo 1',
            'aliases' => ['1 - Control', 'Tipo1'],
            'record_type' => 1,
            'header_row' => 1,
            'data_start_row' => 2,
            'detect_data_start' => true,
            'is_control' => true,
            'has_consecutive' => false,
            'required_sheet' => true,
            'min_records' => 1,
            'max_records' => 1,
            'columns' => [
                ['name' => 'Tipo de registro', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1']],
                ['name' => 'Código de habilitación de la IPS', 'type' => 'A', 'required' => true, 'max' => 12],
                ['name' => 'Tipo de identificación de la IPS', 'type' => 'A', 'required' => true, 'max' => 3, 'allowed' => ['NI','NIT']],
                ['name' => 'Número de identificación de la IPS', 'type' => 'A', 'required' => true, 'max' => 12],
                ['name' => 'Fecha inicial del período', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Fecha final del período', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Número total de registros de detalle', 'type' => 'N', 'required' => true, 'max' => 10],
            ],
        ],

        'tipo2' => [
            'name' => 'Tipo 2',
            'aliases' => ['2 - Oportunidad en citas', 'Tipo2'],
            'record_type' => 2,
            'header_row' => 2,
            'data_start_row' => 3,
            'detect_data_start' => true,
            'required_sheet' => true,
            'min_records' => 0,
            'columns' => [
                ['name' => 'Tipo de registro', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['2']],
                ['name' => 'Consecutivo de registro', 'type' => 'N', 'required' => true, 'max' => 10],
                ...$personFields,
                [
                    'name' => 'Tipo de cita o procedimiento no quirúrgico',
                    'type' => 'N',
                    'required' => true,
                    'max' => 1,
                    'allowed' => ['1','2','3','4','5','6','7','8','9'],
                    'allowed_labels' => [
                        '1' => 'Consulta de primera vez de Medicina General',
                        '2' => 'Consulta de primera vez de Odontología General',
                        '3' => 'Consulta de primera vez de Medicina Interna',
                        '4' => 'Consulta de primera vez de Pediatría',
                        '5' => 'Consulta de primera vez de Ginecología',
                        '6' => 'Consulta de primera vez de Obstetricia',
                        '7' => 'Consulta de primera vez de Cirugía General',
                        '8' => 'Procedimiento de Ecografía',
                        '9' => 'Procedimiento de Resonancia Magnética Nuclear',
                    ],
                    'help' => 'Debe registrar uno de los códigos numéricos permitidos del 1 al 9.',
                ],
                ['name' => 'Fecha de solicitud de la cita', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'La cita fue asignada', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Fecha de asignación de la cita', 'type' => 'F', 'required' => false, 'max' => 10],
                ['name' => 'Fecha deseada por el usuario', 'type' => 'F', 'required' => true, 'max' => 10],
            ],
        ],

        'tipo3' => [
            'name' => 'Tipo 3',
            'aliases' => ['3 - Satisfacción global', 'Tipo3'],
            'record_type' => 3,
            'header_row' => 2,
            'data_start_row' => 3,
            'detect_data_start' => true,
            'required_sheet' => true,
            'min_records' => 0,
            'max_records' => 1,
            'columns' => [
                ['name' => 'Tipo de registro', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['3']],
                ['name' => 'Consecutivo de registro', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Tipo de identificación de la entidad reportadora', 'type' => 'A', 'required' => true, 'max' => 3, 'allowed' => ['NI','NIT']],
                ['name' => 'Número de identificación de la entidad reportadora', 'type' => 'A', 'required' => true, 'max' => 12],
                ['name' => 'Usuarios que respondieron muy buena', 'type' => 'N', 'required' => true, 'max' => 7],
                ['name' => 'Usuarios que respondieron buena', 'type' => 'N', 'required' => true, 'max' => 7],
                ['name' => 'Usuarios que respondieron regular', 'type' => 'N', 'required' => true, 'max' => 7],
                ['name' => 'Usuarios que respondieron mala', 'type' => 'N', 'required' => true, 'max' => 7],
                ['name' => 'Usuarios que respondieron muy mala', 'type' => 'N', 'required' => true, 'max' => 7],
                ['name' => 'Usuarios sin respuesta de experiencia global', 'type' => 'N', 'required' => true, 'max' => 7],
                ['name' => 'Usuarios que respondieron definitivamente sí', 'type' => 'N', 'required' => true, 'max' => 7],
                ['name' => 'Usuarios que respondieron probablemente sí', 'type' => 'N', 'required' => true, 'max' => 7],
                ['name' => 'Usuarios que respondieron definitivamente no', 'type' => 'N', 'required' => true, 'max' => 7],
                ['name' => 'Usuarios que respondieron probablemente no', 'type' => 'N', 'required' => true, 'max' => 7],
                ['name' => 'Usuarios sin respuesta de recomendación', 'type' => 'N', 'required' => true, 'max' => 7],
            ],
        ],

        'tipo4' => [
            'name' => 'Tipo 4',
            'aliases' => ['4 - Procedimientos quirúrgicos', 'Tipo4'],
            'record_type' => 4,
            'header_row' => 2,
            'data_start_row' => 3,
            'detect_data_start' => true,
            'required_sheet' => true,
            'min_records' => 0,
            'columns' => [
                ['name' => 'Tipo de registro', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['4']],
                ['name' => 'Consecutivo de registro', 'type' => 'N', 'required' => true, 'max' => 10],
                ...$personFields,
                ['name' => 'Código del municipio de residencia', 'type' => 'N', 'required' => true, 'max' => 5],
                ['name' => 'Código del procedimiento quirúrgico', 'type' => 'N', 'required' => true, 'max' => 6],
                ['name' => 'Fecha de solicitud de programación', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Fecha de programación', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Se realizó el procedimiento', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
                ['name' => 'Causa de no realización', 'type' => 'N', 'required' => false, 'max' => 1, 'allowed' => ['1','2','3']],
                ['name' => 'Se reprogramó el procedimiento', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['1','2']],
            ],
        ],

        'tipo5' => [
            'name' => 'Tipo 5',
            'aliases' => ['5 - Eventos adversos', 'Tipo5'],
            'record_type' => 5,
            'header_row' => 2,
            'data_start_row' => 3,
            'detect_data_start' => true,
            'required_sheet' => true,
            'min_records' => 0,
            'max_records' => 1,
            'columns' => [
                ['name' => 'Tipo de registro', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['5']],
                ['name' => 'Consecutivo de registro', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Tipo de identificación de la entidad reportadora', 'type' => 'A', 'required' => true, 'max' => 3, 'allowed' => ['NI','NIT']],
                ['name' => 'Número de identificación de la entidad reportadora', 'type' => 'A', 'required' => true, 'max' => 12],
                ['name' => 'Caídas en hospitalización', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Caídas en urgencias', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Caídas en consulta externa', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Caídas en apoyo diagnóstico', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Caídas clasificadas como evento adverso', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Caídas clasificadas como incidente', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Eventos adversos por medicamentos en hospitalización', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Eventos adversos por medicamentos en urgencias', 'type' => 'N', 'required' => true, 'max' => 10],
                ['name' => 'Pacientes con úlceras por presión', 'type' => 'N', 'required' => true, 'max' => 5],
            ],
        ],

        'tipo6' => [
            'name' => 'Tipo 6',
            'aliases' => ['6 - Urgencias Triage II', 'Tipo6'],
            'record_type' => 6,
            'header_row' => 2,
            'data_start_row' => 3,
            'detect_data_start' => true,
            'required_sheet' => false,
            'min_records' => 0,
            'columns' => [
                ['name' => 'Tipo de registro', 'type' => 'N', 'required' => true, 'max' => 1, 'allowed' => ['6']],
                ['name' => 'Consecutivo de registro', 'type' => 'N', 'required' => true, 'max' => 10],
                ...$personFields,
                ['name' => 'Fecha de clasificación TRIAGE II', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Hora de clasificación TRIAGE II', 'type' => 'H', 'required' => true, 'max' => 5],
                ['name' => 'Fecha de atención en urgencias', 'type' => 'F', 'required' => true, 'max' => 10],
                ['name' => 'Hora de atención en urgencias', 'type' => 'H', 'required' => true, 'max' => 5],
            ],
        ],

    ],
];